### ISSUE TITLE
annoying warning

### ISSUE THREAD

**Issue by cordoval** [rollerworks/RollerworksSearch#68]
I think this is not needed really?

```bash
Deprecated: Since v1.0.0-beta3 the service files "services" and "type" are automatically loaded. in /Users/cordoval/Sites/hospice-system/vendor/rollerworks/search-symfony-di/src/ServiceLoader.php on line 52

Call Stack:
```

**Comment by cordoval** [comment]
@sstok i think it is ok to support BC but when package is not stable i think we should just keep code simpler, it confuses newbies like me :older_man:

**Comment by sstok** [comment]
Indeed :+1: its not really a problem.

**Comment by sstok** [comment]
Done by https://github.com/rollerworks/rollerworks-search-symfony-di/pull/9
