### ISSUE TITLE
PATTERN_EQALS for PatternMatch

### ISSUE THREAD

**Issue by sstok** [rollerworks/RollerworksSearch#79]
PatternMatch supports many types but not an exact match (`^pattern$` as regex) making it really hard to do case insensitive matching for text fields. *SingleValue should not be used for this as this will break the contract for non-text values.*

And should also have negative type ;)

**Comment by sstok** [comment]
I forgot to update the exporters :hammer: 

![635412533686232669](https://cloud.githubusercontent.com/assets/904790/9174029/f738f9be-3f7d-11e5-8f6d-402a5d9b0b64.png)

**Comment by cordoval** [comment]
hu hu, where do you find these interesting graphics, very memorable

**Comment by sstok** [comment]
Google :) just google "facepalm"

**Comment by sstok** [comment]
fixed by #81
